[package]
name = "nan-serve-dal-tx-impl"
version = "0.1.0"
edition = "2021"
authors = ["Maxwell Flitton"]
description = "A collection of utilities for nanoservices"
license = "MIT"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.95", features = ["full"] }

[lib]
proc-macro = true
