[package]
name = "api-code-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.95", features = ["full"] }
quote = "1.0.38"
proc-macro2 = "1.0.92"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"

[lib]
proc-macro = true
