[package]
name = "nan-serve-event-subscriber"
version = "0.1.0"
edition = "2021"
authors = ["Maxwell Flitton"]
description = "Tokio event subscriber for nanoservices"
license = "MIT"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.90", features = ["full"] }

[lib]
proc-macro = true
